/**
 * 进行定义请求Action类型
 */
'use strict';

export const PERFORM_LOGIN_ACTION = 'PERFORM_LOGIN_ACTION';
export const RECEIVE_LOGIN_ACTION = 'RECEIVE_LOGIN_ACTION';

export const PERFORM_REGISTER_ACTION = 'PERFORM_REGISTER_ACTION'; //用户注册

export const RECEIVE_CLASSIFY_ACTION = 'RECEIVE_CLASSIFY_ACTION'; //分类列表
export const RECEIVE_ACTIVE_ACTION = 'RECEIVE_ACTIVE_ACTION'; //分类列表点击事件

export const RECEIVE_GOODSLIST_ACTION = 'RECEIVE_GOODSLIST_ACTION'; //商品列表

export const RECEIVE_GOODSDETAIL_ACTION = 'RECEIVE_GOODSDETAIL_ACTION' //商品详情

export const RECEIVE_USER_ACTION = 'RECEIVE_USER_ACTION' //用户个人信息

export const RECEIVE_APPMAIN_ACTION = 'RECEIVE_APPMAIN_ACTION' //AppMain
