/**
 * 进行定义请求Action类型
 */
'use strict';

export const PERFORM_LOGIN_ACTION = 'PERFORM_LOGIN_ACTION';
export const RECEIVE_LOGIN_ACTION = 'RECEIVE_LOGIN_ACTION';

export const PERFORM_REGISTER_ACTION = 'PERFORM_REGISTER_ACTION'; //用户注册

export const RECEIVE_INDEX_ACTION = 'RECEIVE_INDEX_ACTION'//首页数据

export const RECEIVE_CLASSIFY_ACTION = 'RECEIVE_CLASSIFY_ACTION'; //分类列表
export const RECEIVE_ACTIVE_ACTION = 'RECEIVE_ACTIVE_ACTION'; //分类列表点击事件

export const RECEIVE_GOODSLIST_ACTION = 'RECEIVE_GOODSLIST_ACTION'; //商品列表

export const RECEIVE_GOODSDETAIL_ACTION = 'RECEIVE_GOODSDETAIL_ACTION' //商品详情

export const RECEIVE_USER_ACTION = 'RECEIVE_USER_ACTION' //用户个人信息

export const PERFORM_UPDATE_USERINFORM_ACTION = 'PERFORM_UPDATE_USERINFORM_ACTION' //个人信息更新开始

export const RECEIVE_UPDATE_USERINFORM_ACTION = 'RECEIVE_UPDATE_USERINFORM_ACTION' //个人信息更新成功

export const RECEIVE_APPMAIN_ACTION = 'RECEIVE_APPMAIN_ACTION' //AppMain

export const RECEIVE_CART_ACTION = 'RECEIVE_CART_ACTION' //购物车

export const CHANGE_CART_ACTION = 'CHANGE_CART_ACTION' //更改购物车

export const RECEIVE_NLL_CART_ACTION = 'RECEIVE_NLL_CART_ACTION' //购物车为空

export const RECEIVE_ADS_ACTION = 'RECEIVE_ADS_ACTION' //广告管理

export const TOKEN_REFRESH = 'TOKEN_REFRESH' //token过期处理

export const IS_LOGIN = 'IS_LOGIN' //登录成功

export const RECEIVE_ORDER_DISPATCH_ACTION = 'RECEIVE_ORDER_DISPATCH_ACTION' //订单配送方式选择

export const RECEIVE_ADDRESS_ACTION = 'RECEIVE_ADDRESS_ACTION' //收货地址

export const RECEIVE_NLL_ADDRESS_ACTION = 'RECEIVE_NLL_ADDRESS_ACTION' //收货地址为空

export const RECEIVE_ADDRESS_REFRESH_ACTION = 'RECEIVE_ADDRESS_REFRESH_ACTION' //收货地址需要更新

export const RECEIVE_ADD_ACTION = 'RECEIVE_ADD_ACTION' //省市区初始化

export const RECEIVE_PROVINCE_ACTION = 'RECEIVE_PROVINCE_ACTION' //获取省

export const RECEIVE_CITY_ACTION = 'RECEIVE_CITY_ACTION' //获取市

export const RECEIVE_AREA_ACTION = 'RECEIVE_AREA_ACTION' //获取区

export const RECEIVE_CHOOSE_ADDRESS_ACTION = 'RECEIVE_CHOOSE_ADDRESS_ACTION' //收货地址选择
